---
development:
  dialect: "sqlite3"
  database: go_goals_development.sqlite

test:
  dialect: "sqlite3"
  database: go_goals_test.sqlite

production:
  dialect: "sqlite3"
  database: go_goals_production.sqlite
