package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"go_goals/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Note)
// DB Table: Plural (notes)
// Resource: Plural (Notes)
// Path: Plural (/notes)
// View Template Folder: Plural (/templates/notes/)

// NotesResource is the resource for the Note model
type NotesResource struct {
	buffalo.Resource
}

// List gets all Notes. This function is mapped to the path
// GET /notes
func (v NotesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	notes := &models.Notes{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Notes from the DB
	if err := q.All(notes); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("notes", notes)
		return c.Render(http.StatusOK, r.HTML("notes/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(notes))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(notes))
	}).Respond(c)
}

// Show gets the data for one Note. This function is mapped to
// the path GET /notes/{note_id}
func (v NotesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Note
	note := &models.Note{}

	// To find the Note the parameter note_id is used.
	if err := tx.Find(note, c.Param("note_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("note", note)

		return c.Render(http.StatusOK, r.HTML("notes/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(note))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(note))
	}).Respond(c)
}

// New renders the form for creating a new Note.
// This function is mapped to the path GET /notes/new
func (v NotesResource) New(c buffalo.Context) error {
	c.Set("note", &models.Note{})

	return c.Render(http.StatusOK, r.HTML("notes/new.plush.html"))
}

// Create adds a Note to the DB. This function is mapped to the
// path POST /notes
func (v NotesResource) Create(c buffalo.Context) error {
	// Allocate an empty Note
	note := &models.Note{}

	// Bind note to the html form elements
	if err := c.Bind(note); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(note)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("note", note)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("notes/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "note.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/notes/%v", note.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(note))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(note))
	}).Respond(c)
}

// Edit renders a edit form for a Note. This function is
// mapped to the path GET /notes/{note_id}/edit
func (v NotesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Note
	note := &models.Note{}

	if err := tx.Find(note, c.Param("note_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("note", note)
	return c.Render(http.StatusOK, r.HTML("notes/edit.plush.html"))
}

// Update changes a Note in the DB. This function is mapped to
// the path PUT /notes/{note_id}
func (v NotesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Note
	note := &models.Note{}

	if err := tx.Find(note, c.Param("note_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Note to the html form elements
	if err := c.Bind(note); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(note)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("note", note)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("notes/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "note.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/notes/%v", note.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(note))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(note))
	}).Respond(c)
}

// Destroy deletes a Note from the DB. This function is mapped
// to the path DELETE /notes/{note_id}
func (v NotesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Note
	note := &models.Note{}

	// To find the Note the parameter note_id is used.
	if err := tx.Find(note, c.Param("note_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(note); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "note.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/notes")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(note))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(note))
	}).Respond(c)
}
