package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"go_goals/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Note)
// DB Table: Plural (notes)
// Resource: Plural (Notes)
// Path: Plural (/notes)
// View Template Folder: Plural (/templates/notes/)

// NotesResource is the resource for the Note model
type NotesResource struct {
	buffalo.Resource
}

func setPageContextForNotes(c buffalo.Context) {
	userOptions := make(map[string]string)
	userIdsToNameMap := make(map[string]string)
	users := []models.User{}
	err := models.DB.All(&users)
	if err == nil {
		for _, user := range users {
			userOptions[user.Name] = user.ID.String()
			userIdsToNameMap[user.ID.String()] = user.Name
		}
	} else {
		c.Logger().Errorf("Error getting users: %v", err)
	}
	c.Set("userOptions", userOptions)
	c.Set("userIdsToNameMap", userIdsToNameMap)

	currentUser := c.Value("current_user").(*models.User)
	goalOptions := make(map[string]string)
	var goalIds []interface{}
	goalIdsToNameMap := make(map[string]string)
	goals := []models.Goal{}
	err = models.DB.Where("user_id = ?", currentUser.ID).Where("active = true").All(&goals)
	if err == nil {
		for _, goal := range goals {
			goalIds = append(goalIds, goal.ID.String())
			goalOptions[goal.Title] = goal.ID.String()
			goalIdsToNameMap[goal.ID.String()] = goal.Title
		}
	} else {
		c.Logger().Errorf("Error getting goals: %v", err)
	}
	c.Set("goalOptions", goalOptions)
	c.Set("goalIdsToNameMap", goalIdsToNameMap)

	milestoneOptions := make(map[string]string)
	milestoneIdsToNameMap := make(map[any]string)
	milestones := []models.Milestone{}
	var milestoneIds []interface{}
	err = models.DB.Where("goal_id in (?)", goalIds...).All(&milestones)
	if err == nil {
		for _, milestone := range milestones {
			milestoneIds = append(milestoneIds, milestone.ID.String())
			milestoneOptions[milestone.Title] = milestone.ID.String()
			milestoneIdsToNameMap[milestone.ID.String()] = milestone.Title
		}
	} else {
		c.Logger().Errorf("Error getting milestones: %v", err)
	}
	c.Set("milestoneOptions", milestoneOptions)
	c.Set("milestoneIdsToNameMap", milestoneIdsToNameMap)

	taskOptions := make(map[string]string)
	taskIdsToNameMap := make(map[any]string)
	tasks := []models.Task{}
	var taskIds []interface{}
	err = models.DB.Where("goal_id in (?)", goalIds...).All(&tasks)
	if err == nil {
		for _, task := range tasks {
			taskIds = append(taskIds, task.ID.String())
			taskOptions[task.Title] = task.ID.String()
			taskIdsToNameMap[task.ID.String()] = task.Title
		}
	} else {
		c.Logger().Errorf("Error getting tasks: %v", err)
	}
	c.Set("taskOptions", taskOptions)
	c.Set("taskIdsToNameMap", taskIdsToNameMap)

	noteOptions := make(map[string]string)
	noteIdsToNameMap := make(map[any]string)

	goalNotes := []models.Note{}
	err = models.DB.Where("goal_id in (?)", goalIds...).All(&goalNotes)
	if err == nil {
		for _, note := range goalNotes {
			noteOptions[note.Title] = note.ID.String()
			noteIdsToNameMap[note.ID.String()] = note.Title
		}
	} else {
		c.Logger().Errorf("Error getting notes: %v", err)
	}

	milestoneNotes := []models.Note{}
	err = models.DB.Where("milestone_id in (?)", milestoneIds...).All(&milestoneNotes)
	if err == nil {
		for _, note := range milestoneNotes {
			noteOptions[note.Title] = note.ID.String()
			noteIdsToNameMap[note.ID.String()] = note.Title
		}
	} else {
		c.Logger().Errorf("Error getting notes: %v", err)
	}

	taskNotes := []models.Note{}
	err = models.DB.Where("task_id in (?)", taskIds...).All(&taskNotes)
	if err == nil {
		for _, note := range taskNotes {
			noteOptions[note.Title] = note.ID.String()
			noteIdsToNameMap[note.ID.String()] = note.Title
		}
	} else {
		c.Logger().Errorf("Error getting notes: %v", err)
	}
	c.Set("noteOptions", noteOptions)
	c.Set("noteIdsToNameMap", noteIdsToNameMap)
}

// List gets all Notes. This function is mapped to the path
// GET /notes
func (v NotesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	notes := &models.Notes{}
	setPageContextForNotes(c)

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Notes from the DB
	if err := q.All(notes); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("notes", notes)
		return c.Render(http.StatusOK, r.HTML("notes/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(notes))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(notes))
	}).Respond(c)
}

// Show gets the data for one Note. This function is mapped to
// the path GET /notes/{note_id}
func (v NotesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Note
	note := &models.Note{}
	setPageContextForNotes(c)

	// To find the Note the parameter note_id is used.
	if err := tx.Find(note, c.Param("note_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("note", note)

		return c.Render(http.StatusOK, r.HTML("notes/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(note))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(note))
	}).Respond(c)
}

// New renders the form for creating a new Note.
// This function is mapped to the path GET /notes/new
func (v NotesResource) New(c buffalo.Context) error {
	c.Set("note", &models.Note{})
	setPageContextForNotes(c)

	return c.Render(http.StatusOK, r.HTML("notes/new.plush.html"))
}

// Create adds a Note to the DB. This function is mapped to the
// path POST /notes
func (v NotesResource) Create(c buffalo.Context) error {
	// Allocate an empty Note
	note := &models.Note{}
	setPageContextForNotes(c)

	// Bind note to the html form elements
	if err := c.Bind(note); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(note)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("note", note)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("notes/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "note.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/notes/%v", note.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(note))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(note))
	}).Respond(c)
}

// Edit renders a edit form for a Note. This function is
// mapped to the path GET /notes/{note_id}/edit
func (v NotesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Note
	note := &models.Note{}
	setPageContextForNotes(c)

	if err := tx.Find(note, c.Param("note_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("note", note)
	return c.Render(http.StatusOK, r.HTML("notes/edit.plush.html"))
}

// Update changes a Note in the DB. This function is mapped to
// the path PUT /notes/{note_id}
func (v NotesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Note
	note := &models.Note{}

	if err := tx.Find(note, c.Param("note_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Note to the html form elements
	if err := c.Bind(note); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(note)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("note", note)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("notes/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "note.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/notes/%v", note.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(note))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(note))
	}).Respond(c)
}

// Destroy deletes a Note from the DB. This function is mapped
// to the path DELETE /notes/{note_id}
func (v NotesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Note
	note := &models.Note{}

	// To find the Note the parameter note_id is used.
	if err := tx.Find(note, c.Param("note_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(note); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "note.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/notes")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(note))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(note))
	}).Respond(c)
}
